spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/payment
    password: pass
    username: pay
#  main:
#    web-application-type: reactive
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  servlet:
    context-path: /ipg

springdoc:
  swagger-ui:
    path: /swagger-ui.html
#
#eureka:
#  client:
#    register-with-eureka: false